---
title: "FATE-HD tutorial - Building PFG"
# author: "LECA Grenoble"
# date: "10/05/2016"
output:
  html_document:
    theme: lumen
    highlight: zenburn
    number_sections: no
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

<br/> <br/>


A plant functional group, or **PFG**, is "*A set of representative species is classified based on key biological characteristics, to determine groups of species sharing ecological strategies*" ([Boulangeat, 2012](http://j.boulangeat.free.fr/pdfs/Boulangeat2012_GCB_published.pdf "Boulangeat, I., Philippe, P., Abdulhak, S., Douzet, R., Garraud, L., Lavergne, S., Lavorel, S., Van Es J., Vittoz, P. and Thuiller, W. Improving plant functional groups for dynamic models of biodiversity: at the crossroad between functional and community ecology. Global Change Biology, 18, 3464-3475.")).

<br/> <br/>

[RFate](https://mayagueguen.github.io/RFate/) is a [R](https://www.r-project.org/) package available on [github](https://github.com/MayaGueguen/RFate) and designed to provide support function to the `FATE-HD` software.

It contains documentation and functions to create and organize all input files required by the model, and **building PFG** is the first step to run a `FATE-HD` simulation. The procedure presented below is based on `RFate` functions.

<br/> <br/>


# <i class="fa fa-shoe-prints"></i> What are the key steps of this process ?

<br/>
Since the basic idea of building Functional Group is to gather a lot of elements into a few, this implies two requirements :

- that these elements are not too numerous
- and that they are representative of the studied area, meaning not rare or outlier elements.  
**This is the first step of selecting dominant species.**

In order to identify similarities between selected dominant species in terms of habitat, the climatic or environmental niche of each species is calculated and is compared with all the other dominant species niches.  
**The overlap of species climatic niches is obtained in second step.**

Functional traits related to the fundamental process of growth are retrieved for each dominant species and mixed together to calculate functional distances between species.  
**Overlap of climatic niches and functional distances are combined to form a matrix of species pairwise distances.**

Finally, based on this distance matrix, **species are clustered to find the best combination and obtain Functional Groups.**

<br/> <br/>

# <i class="fa fa-shopping-basket"></i> What do you need ?

<br/>

### 1. Selection of dominant species

- Gather **occurrences** for all species within the studied area
- Identify **dominant species** based on abundances and frequençy of sampling

with the function [PRE_FATE.selectDominant](https://mayagueguen.github.io/RFate/reference/PRE_FATE.selectDominant.html)  

<br/>

### 2. Overlap of species climatic niches
with either Principal Component Analysis (PCA) or Species Distribution Models (SDM)

- *Option 1: Principal Component analysis*
    - Gather **environmental data** for the studied area
    - Compute **PCA** over environment to create a *climatic space*
    - Calculate the **density of each species** within this *climatic space* from the PCA
    - For each pair of species, compute the **overlap** of the 2 considered species within the *climatic space*

<br/>

- *Option 2: Species Distribution Models*
    - Gather **environmental data** for the studied area
    - For each dominant species, compute a **species distribution model** (SDM)  
    combining environmental data and occurrences to determine the *climatic niche* of the species
    - With these SDMs, calculate the **niche overlap** of each pair of species

<br/>

### 3. Calculation of species pairwise distance
by combining overlap and functional distances with the function [PRE_FATE.speciesDistance](https://mayagueguen.github.io/RFate/reference/PRE_FATE.speciesDistance.html)

- Gather **traits data** for all dominant species within the studied area  
(traits need to be related to fundamental process of growth : light tolerance, dispersal, height...)
- Compute **dissimilarity distances** between pairs of species based on these traits and taking also into account the overlap of the 2 species within the *climatic space* (see previous step)

*For further details about the data, please refer to* [Boulangeat, 2012](http://j.boulangeat.free.fr/pdfs/Boulangeat2012_GCB_published.pdf "Boulangeat, I., Philippe, P., Abdulhak, S., Douzet, R., Garraud, L., Lavergne, S., Lavorel, S., Van Es J., Vittoz, P. and Thuiller, W. Improving plant functional groups for dynamic models of biodiversity: at the crossroad between functional and community ecology. Global Change Biology, 18, 3464-3475."). 

<br/>

### 4. Clustering of species
using the **dissimilarity distances** from previous step :

- calculate all possible clusters, and the corresponding evaluation metrics  
with the function [PRE_FATE.speciesClustering_step1](https://mayagueguen.github.io/RFate/reference/PRE_FATE.speciesClustering_step1.html)
- choose the best number of clusters from the previous step and find determinant species  
with the function [PRE_FATE.speciesClustering_step2](https://mayagueguen.github.io/RFate/reference/PRE_FATE.speciesClustering_step2.html)

