---
title: "<font color='#068f96'> <i class='fa fa-battery-three-quarters'></i> `POST_FATE` - graphics </font>"
---


<br/>


*A. Evolution of simulation through time*

- **Create temporal evolution table** : retrieve PFG pixel abundance (as well as light and soil resources) through time  
with the function [POST_FATE.temporalEvolution](https://mayagueguen.github.io/RFate/reference/POST_FATE.temporalEvolution.html)
- **Abundance over all studied area** : with the function [POST_FATE.graphic_evolutionCoverage](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_evolutionCoverage.html)
- **Abundance / light / soil within some pixels** : with the function [POST_FATE.graphic_evolutionPixels](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_evolutionPixels.html)


*B. Evaluation of outputs*

- **Create relative abundance maps** : transform absolute abundance maps into relative abundance maps  
with the function [POST_FATE.relativeAbund](https://mayagueguen.github.io/RFate/reference/POST_FATE.relativeAbund.html)
- **Validation statistics** : calculate evaluation metrics (TSS, AUC) for each PFG, and transform relative abundance maps into presence / absence with the function [POST_FATE.graphic_validationStatistics](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_validationStatistics.html)
- **PFG outputs vs Habitat suitability** : compare binary maps (outputs) with habitat suitability maps (inputs)  
with the function [POST_FATE.graphic_mapPFGvsHS](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_mapPFGvsHS.html)


*C. Visualization of outputs*

- **PFG richness** : create map of number of PFG alive within each pixel  
with the function [POST_FATE.graphic_mapPFGrichness](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_mapPFGrichness.html)
- **PFG cover** : create map of PFG abundance above 1.5 meters within each pixel  
with the function [POST_FATE.graphic_mapPFGcover](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_mapPFGcover.html)
- **PFG CWM of light** : create map of light community weighted mean within each pixel  
with the function [POST_FATE.graphic_mapPFGlight](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_mapPFGlight.html)
- **PFG CWM of soil** : create map of soil community weighted mean within each pixel  
with the function [POST_FATE.graphic_mapPFGsoil](https://mayagueguen.github.io/RFate/reference/POST_FATE.graphic_mapPFGsoil.html)


